name: Build
description: Create a new Docker image
inputs:
  dockerfile_path:
    description: "Path to the Dockerfile"
    required: false
    default: "Dockerfile"
  image_name:
    description: "Image name"
    required: false
    default: "academy"
  tag_name:
    description: "Tag name"
    required: false
runs:
  using: composite
  steps:
    - name: Define env variables
      shell: bash
      run: |
        if [ -z "${{ inputs.tag_name }}" ]; then
          TAG=$(date +%s) >> $GITHUB_ENV
        else
          TAG=${{ inputs.tag_name }} >> $GITHUB_ENV
        fi
        
        PATH=${{ inputs.dockerfile_path }}
        NAME=${{ inputs.image_name }} >> $GITHUB_ENV

    - name: Create docker image
      shell: bash
      run: |
        docker build . --file $PATH --tag $NAME:$TAG