name: Build
description: Create a new Docker image
inputs:
  dockerfile_path:
    description: "Path to the Dockerfile"
    required: false
    default: "Dockerfile"
  image_name:
    description: "Image name"
    required: false
    default: "academy"
  tag_name:
    description: "Tag name"
    required: false
runs:
  using: composite
  steps:
    - name: Define env variables
      shell: bash
      run: |
        if [ -z "${{ inputs.tag_name }}" ]; then
          echo "TAG=$(date +%s)" >> $GITHUB_ENV
        else
          echo "TAG=${{ inputs.tag_name }}" >> $GITHUB_ENV
        fi
        
        echo "PATH=${{ inputs.dockerfile_path }}"
        echo "NAME=${{ inputs.image_name }}" >> $GITHUB_ENV

    - name: Create docker image
      shell: bash
      run: |
        docker build . --file $PATH --tag $NAME:$TAG