name: Build
description: Push image to docker hub
inputs:
  docker_username:
    description: "Docker hub username"
    required: true
  docker_token:
    description: "Docker hub token"
    required: true
  image_name:
    description: "Image name"
    required: true
runs:
  using: composite
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_token }}
    - name: Tag the image
      shell: bash
      run: |
        docker tag ${{ inputs.image_name }} ${{ inputs.docker_username }}/${{ inputs.image_name }}
        docker push ${{ inputs.docker_username }}/${{ inputs.image_name }}