name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      uses: danielagoncalves12/academy/.github/actions/maven_build@main
    - name: Build the docker file
      uses: danielagoncalves12/academy/.github/actions/docker_build@main
      with:
        dockerfile_path: src/main/docker/Dockerfile.jvm
    - name: List docker images
      run: docker images
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}